// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPuFk-ArFvN1rm-NDkNd2JEDOkEmHrog',
    appId: '1:867401004624:web:610cb25c45ac332c8b8355',
    messagingSenderId: '867401004624',
    projectId: 'mohamed-arshath-test-file',
    authDomain: 'mohamed-arshath-test-file.firebaseapp.com',
    storageBucket: 'mohamed-arshath-test-file.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTNXO4egoNyCH2di9rkl4R3-yxoG-3wGU',
    appId: '1:867401004624:android:40a43734dec674018b8355',
    messagingSenderId: '867401004624',
    projectId: 'mohamed-arshath-test-file',
    storageBucket: 'mohamed-arshath-test-file.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIwa1pBvhKdlHmevSq5mWo_DD98B1uscM',
    appId: '1:867401004624:ios:4fbebb2f2fb4ee7f8b8355',
    messagingSenderId: '867401004624',
    projectId: 'mohamed-arshath-test-file',
    storageBucket: 'mohamed-arshath-test-file.appspot.com',
    iosBundleId: 'com.example.arshathTestFile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIwa1pBvhKdlHmevSq5mWo_DD98B1uscM',
    appId: '1:867401004624:ios:bfb0fd798ab1eab68b8355',
    messagingSenderId: '867401004624',
    projectId: 'mohamed-arshath-test-file',
    storageBucket: 'mohamed-arshath-test-file.appspot.com',
    iosBundleId: 'com.example.arshathTestFile.RunnerTests',
  );
}
